sudo: required
dist: trusty
language: node_js
group: deprecated-2017Q2
node_js:
  - '6.11.2'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - 
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
# npm install
- npm install
- npm install -g express 
